version: '3.3'

networks:
  prod_external:
    internal: false
  prod_internal:
    internal: true

services:
  prod_elasticsearch:
    container_name: prod_elasticsearch
    image: ryanschuhler/elasticsearch:ism
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "prod_elasticsearch:/usr/share/elasticsearch/data"
  prod_mockmock:
    container_name: prod_mockmock
    image: ryanschuhler/mockmock:ism
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "8282:8282"
    volumes:
      - "prod_mockmock:/home"
  web_prod_httpd:
    container_name: web_prod_httpd
    environment:
      - "EXTRA_REWRITE_RULE="
      - "EXTRA_REWRITE_COND="
      - "LIFERAY_CONTAINER_NAME=web_prod_liferay"
      - "SERVER_NAME=localhost"
    image: ryanschuhler/httpd:ism
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "8090:80"
      - "4493:443"
    volumes:
      - "web_prod_httpd:/var/www/html"
      - "./httpd/resources/:/tmp/httpd"
  web_prod_liferay:
    container_name: web_prod_liferay
    depends_on:
     - "web_prod_mariadb"
    environment:
      - "VIRTUAL_PORT=8080"
    image: ryanschuhler/liferay:web-prod
    ports:
      - "8900:8000"
    user: root
    networks:
      - "prod_external"
      - "prod_internal"
    volumes:
      - "web_prod_liferay:/opt/java/liferay/data"
      - "./web-prod/liferay/deploy:/opt/java/liferay/deploy"
  web_prod_mariadb:
    container_name: web_prod_mariadb
    environment:
      - "collation-server=utf8mb4_unicode_ci"
      - "character-set-server=utf8mb4"
      - "MYSQL_PASSWORD=passw0rd"
      - "MYSQL_ROOT_PASSWORD=passw0rd"
      - "MYSQL_DATABASE=lportal"
      - "MYSQL_USER=liferay"
    image: mariadb:10.1
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "3308:3306"
    volumes:
      - "web_prod_mariadb:/var/lib/mysql"
      - "./web-prod/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
  www_prod_httpd:
    container_name: www_prod_httpd
    environment:
      - "EXTRA_REWRITE_RULE="
      - "EXTRA_REWRITE_COND=RewriteRule   '^/documents/(.+)'  'https://www.liferay.com/documents/$$1'"
      - "LIFERAY_CONTAINER_NAME=www_prod_liferay"
      - "SERVER_NAME=localhost"
    image: ryanschuhler/httpd:ism
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "www_prod_httpd:/var/www/html"
      - "./httpd/resources/:/tmp/httpd"
  www_prod_liferay:
    container_name: www_prod_liferay
    depends_on:
     - "www_prod_mariadb"
    environment:
      - "VIRTUAL_PORT=8080"
    image: ryanschuhler/liferay:www-prod
    ports:
      - "8000:8000"
      - "11311:11311"
      - "12345:12345"
    user: root
    networks:
      - "prod_external"
      - "prod_internal"
    volumes:
      - "www_prod_liferay:/opt/java/liferay/data"
      - "./www-prod/liferay/deploy:/opt/java/liferay/deploy"
  www_prod_mariadb:
    container_name: www_prod_mariadb
    environment:
      - "collation-server=utf8mb4_unicode_ci"
      - "character-set-server=utf8mb4"
      - "MYSQL_ROOT_PASSWORD=passw0rd"
      - "MYSQL_DATABASE=lportal"
      - "MYSQL_USER=liferay"
    image: mariadb:10.1.30
    networks:
      - "prod_external"
      - "prod_internal"
    ports:
      - "3307:3306"
    volumes:
      - "www_prod_mariadb:/var/lib/mysql"
      - "./www-prod/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"

volumes:
  prod_elasticsearch:
  prod_mockmock:
  web_prod_httpd:
  web_prod_liferay:
  web_prod_mariadb:
    external:
      name: web-prod_web_prod_mariadb
  www_prod_httpd:
  www_prod_liferay:
  www_prod_mariadb:
    external:
      name: www-prod_www_prod_mariadb